export const InputMapping = {
  ' ': false,
  'backspace': false,
  'tab': false,
  'enter': false,
  'shift': false,
  'control': false,
  'alt': false,
  'pause': false,
  'capslock': false,
  'escape': false,
  'pageup': false,
  'pagedown': false,
  'end': false,
  'home': false,
  'arrowleft': false,
  'uparrow': false,
  'arrowright': false,
  'arrowdown': false,
  'insert': false,
  'delete': false,
  '0': false,
  '1': false,
  '2': false,
  '3': false,
  '4': false,
  '5': false,
  '6': false,
  '7': false,
  '8': false,
  '9': false,
  'a': false,
  'b': false,
  'c': false,
  'd': false,
  'e': false,
  'f': false,
  'g': false,
  'h': false,
  'i': false,
  'j': false,
  'k': false,
  'l': false,
  'm': false,
  'n': false,
  'o': false,
  'p': false,
  'q': false,
  'r': false,
  's': false,
  't': false,
  'u': false,
  'v': false,
  'w': false,
  'x': false,
  'y': false,
  'z': false,
  'meta': false,
  'select key': false,
  'numpad 0': false,
  'numpad 1': false,
  'numpad 2': false,
  'numpad 3': false,
  'numpad 4': false,
  'numpad 5': false,
  'numpad 6': false,
  'numpad 7': false,
  'numpad 8': false,
  'numpad 9': false,
  '*': false,
  '+': false,
  '-': false,
  '.': false,
  '/': false,
  'f1': false,
  'f2': false,
  'f3': false,
  'f4': false,
  'f5': false,
  'f6': false,
  'f7': false,
  'f8': false,
  'f9': false,
  'f10': false,
  'f11': false,
  'f12': false,
  'numlock': false,
  'scrolllock': false,
  ';': false,
  '=': false,
  ',': false,
  '-': false,
  '.': false,
  '/': false,
  '~': false,
  '[': false,
  '\\': false,
  '[': false,
  '\'': false
};


